# Generated by Django 5.2.7 on 2025-10-28 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la empresa o persona proveedora', max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('producto_suministrado', models.CharField(help_text='Ej: Pan, Carne, Verduras, Empaques', max_length=200)),
                ('logo_proveedor', models.ImageField(blank=True, null=True, upload_to='img_proveedores/')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_insumo', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('L', 'Litros'), ('ml', 'Mililitros'), ('pz', 'Piezas'), ('caja', 'Caja'), ('paq', 'Paquete')], max_length=50)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('imagen_insumo', models.ImageField(blank=True, null=True, upload_to='img_insumos/')),
                ('id_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_inventario', to='app_mcdonalds_inv.proveedor')),
            ],
            options={
                'verbose_name': 'Insumo de Inventario',
                'verbose_name_plural': 'Inventario',
            },
        ),
    ]
